# nom de l'application
spring:
  application:
    name: miagesousleau
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:9000/eureka/
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom/html

server:
  port: 8090
